name: Check branch name
on: 
  pull_request:
    # runs if a pull request is created, a new push is made to an existing pull request, or a pull request is synchronized (updated due to a new push in the pull request's branch), or the base branch is modified
    types: [opened, reopened, synchronize, edited, ready_for_review]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check branch name
      run: |
        if [[ "${{ github.base_ref }}" == "main" && ! "${{ github.head_ref }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid branch name. Only branches with the pattern v*.*.* can be merged into main."
          exit 1
        fi
