name: Check branch name
on: 
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check branch name
      run: |
        if [[ "${{ github.base_ref }}" == "main" && ! "${{ github.head_ref }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid branch name. Only branches with the pattern v*.*.* can be merged into main."
          exit 1
        fi
